WebAdministrativo/Controllers/PontoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebAdministrativo.Dominio;
using WebAdministrativo.Models;

namespace WebAdministrativo.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PontoController : BasicController
    {
        public ActionResult Index()
        {
            IEnumerable<Ponto> pontos = pontoServico.PontosMesAtual().ToList();
            List<PontoListarModel> pontosDoMes = new List<PontoListarModel>();

            foreach (Ponto ponto in pontos)
            {
                PontoListarModel novoPonto;
                novoPonto = pontosDoMes.Where(x => x.Dia.Date == ponto.Dia.Date).FirstOrDefault();
                if (novoPonto != null)
                {
                    novoPonto.AddRegistroPonto(ponto.PontoId, ponto.Entrada, ponto.Saida, ponto.Observacao);
                }
                else
                {
                    novoPonto = new PontoListarModel(ponto.Dia);
                    pontosDoMes.Add(novoPonto);
                    novoPonto.AddRegistroPonto(ponto.PontoId, ponto.Entrada, ponto.Saida, ponto.Observacao);
                }
            }
            return View(pontosDoMes);
        }

        public ActionResult Novo()
        {
            return View("Editar");
        }

        [HttpPost]
        public ActionResult Novo(PontoEditarModel model)
        {
            DateTime? entrada = null;
            DateTime? saida = null;
            if (model.Entrada.HasValue)
                entrada = new DateTime(model.Dia.Year, model.Dia.Month, model.Dia.Day, model.Entrada.Value.Hour, model.Entrada.Value.Minute, model.Entrada.Value.Second);

            if (model.Saida.HasValue)
            {
                if (model.Entrada.HasValue && model.Entrada.Value.Hour > model.Saida.Value.Hour)
                    saida = new DateTime(model.Dia.Year, model.Dia.Month, model.Dia.Day + 1, model.Saida.Value.Hour, model.Saida.Value.Minute, model.Saida.Value.Second);
                else
                    saida = new DateTime(model.Dia.Year, model.Dia.Month, model.Dia.Day, model.Saida.Value.Hour, model.Saida.Value.Minute, model.Saida.Value.Second);
            }

            if (model.PontoId.HasValue)
            {
                Ponto ponto = pontoServico.GetById(model.PontoId.Value);
                if (ponto != null)
                {
                    ponto.Alterar(model.Dia, entrada, saida, model.Observacao);
                    pontoServico.Update(ponto);
                }
            }
            else
            {
                pontoServico.Add(new Ponto(model.Dia, entrada, saida, model.Observacao));
            }
            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id)
        {
            Ponto ponto = pontoServico.GetById(id);
            if (ponto != null)
            {
                PontoEditarModel model = new PontoEditarModel(ponto.PontoId, ponto.Dia, ponto.Entrada, ponto.Saida, ponto.Observacao, ponto.DataCadastro);
                return View("Editar", model);
            }
            return View("Editar");
        }

        public ActionResult Delete(int id)
        {
            Ponto ponto = pontoServico.GetById(id);
            if (ponto != null)
            {
                pontoServico.Delete(ponto);
            }
            return RedirectToAction("Index");
        }

    }
}

WebAdministrativo/Views/Ponto/Editar.cshtml
@model WebAdministrativo.Models.PontoEditarModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>
@using (Html.BeginForm("Novo", "Ponto"))
{
    @Html.ValidationSummary(false, "ATENÇÃO:", new { @class = "alert alert-error" })  
    @Html.HiddenFor(x => x.PontoId) 
    <div class="Linha">
        <div class="editor-label">
            @Html.LabelFor(model => model.Dia)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Dia, new { @Value = Model != null ? Model.Dia.ToString("dd/MM/yyyy") : string.Empty, @class = "input-xlarge" })
        </div>
    </div>
    <div class="Linha">
        <div class="editor-label">
            @Html.LabelFor(model => model.Entrada)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Entrada, new { @Value = Model != null && Model.Entrada.HasValue ? Model.Entrada.Value.ToString("HH:mm") : string.Empty, @class = "input-xlarge" })
        </div>
    </div>
    <div class="Linha">
        <div class="editor-label">
            @Html.LabelFor(model => model.Saida)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(m => m.Saida, new { @Value = Model != null && Model.Saida.HasValue ? Model.Saida.Value.ToString("HH:mm") : string.Empty, @class = "input-xlarge" })
        </div>
    </div>  
    <div class="Linha">
        <div class="editor-label">
            @Html.LabelFor(model => model.Observacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Observacao)
        </div>
    </div>        
    <p>
        <input type="submit" value="Salvar" class="btn btn-primary" />
        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn" })
    </p>
}

WebAdministrativo/Views/Ponto/Index.cshtml
@model IEnumerable<WebAdministrativo.Models.PontoListarModel>
@{
    ViewBag.Title = "Index";
}

<h2>Pontos</h2>

<p>
    @Html.ActionLink("Cadastrar", "Novo")
</p>
<table>
    <tr>
        <th>
            Dia
        </th>
        <th>
            Entrada / Saída
        </th>
        <th>Sub Total</th>
        <th>Saldo</th>
    </tr>

@foreach (var item in Model) {
    <tr class="linha-registro-@item.Completo">
        <td>
            @item.Dia.ToShortDateString()
        </td>
        <td>
            @foreach (WebAdministrativo.Models.PontoEntradaSaidaModel registro in item.Turnos)
	        {
		        <div>
                    <div class="registro-horario">@(registro.Entrada.HasValue ? registro.Entrada.Value.ToShortTimeString() : "") --> @(registro.Saida.HasValue ? registro.Saida.Value.ToShortTimeString() : "")</div>
                    @Html.ActionLink("Alterar", "Editar", new { id = registro.PontoId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = registro.PontoId }, new { @OnClick = "return confirm('Deseja realmente excluir esse ponto?');" })
                    @*<a class="btn btn-primary" href="#"><i class="icon-align-left icon-white"></i></a>*@
                </div>
            }
        </td>
        <td>@item.TotalDoDia.Value.ToString(@"hh\:mm\:ss")</td>
        <td>@item.SaldoDoDiaFormatado</td>
    </tr>
}

</table>